global:
  scrape_interval: 5s

scrape_configs:
  # 1. 백엔드 API 모니터링
  - job_name: 'murro_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.0.9:31000']

  # 2. [추가됨] 서버 CPU/메모리/디스크 모니터링 (대시보드용)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
