apiVersion: apps/v1
kind: Deployment
metadata:
  name: murro-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murro-backend
  template:
    metadata:
      labels:
        app: murro-backend
    spec:
      imagePullSecrets:      # <--- 추가
        - name: ghcr-secret  # <--- 추가
      containers:
        - name: backend
          image: ghcr.io/team-murro/murro-labs/backend:ba7f77c3
          imagePullPolicy: Always  # [중요] 외부에서 찾지 말고 아까 넣은 로컬 이미지 써라!
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: DB_HOST
              value: "10.42.0.1"  # [핵심] K3s에서 호스트(내 컴퓨터)를 가리키는 마법의 IP입니다.
            - name: OLLAMA_HOST
              value: "http://192.168.0.9:11434"
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
      volumes:
        - name: model-storage
          hostPath:
            path: /home/murro/murro/models  # (아까 만든 서버 폴더)
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: murro-backend-svc
spec:
  type: NodePort
  selector:
    app: murro-backend
  ports:
    - port: 80       # 서비스 포트
      targetPort: 8000 # 컨테이너 포트
      nodePort: 31000
