apiVersion: apps/v1
kind: Deployment
metadata:
  name: murro-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murro-backend
  template:
    metadata:
      labels:
        app: murro-backend
    spec:
      imagePullSecrets:      # <--- 추가
        - name: ghcr-secret  # <--- 추가
      containers:
        - name: backend
          image: ghcr.io/team-murro/murro-labs/backend:latest
          imagePullPolicy: Always  # [중요] 외부에서 찾지 말고 아까 넣은 로컬 이미지 써라!
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: DB_HOST
              value: "10.42.0.1"  # [핵심] K3s에서 호스트(내 컴퓨터)를 가리키는 마법의 IP입니다.
---
apiVersion: v1
kind: Service
metadata:
  name: murro-backend-svc
spec:
  selector:
    app: murro-backend
  ports:
    - port: 80       # 서비스 포트
      targetPort: 8000 # 컨테이너 포트
