apiVersion: apps/v1
kind: Deployment
metadata:
  name: murro-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murro-backend
  template:
    metadata:
      labels:
        app: murro-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/team-murro/murro-labs/backend:ba7f77c3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: DB_HOST
              value: "10.42.0.1"
            - name: OLLAMA_HOST
              value: "http://192.168.0.9:11434"
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
      volumes:
        - name: model-storage
          hostPath:
            path: /home/murro/murro/models
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: murro-backend-svc
spec:
  type: NodePort
  selector:
    app: murro-backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31000
