spec:
  template:
    spec:
      containers:
      - name: argocd-server
        # 1. 문제의 args를 'null'로 해서 강제로 지워버립니다.
        args: null
        # 2. 필요한 모든 명령어를 완벽하게 넣습니다.
        command:
        - argocd-server
        - --staticassets
        - /shared/app
        - --redis
        - argocd-redis:6379
        - --repo-server
        - argocd-repo-server:8081
        - --dex-server
        - http://argocd-dex-server:5556
        - --insecure
