apiVersion: apps/v1
kind: Deployment
metadata:
  name: murro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murro-frontend
  template:
    metadata:
      labels:
        app: murro-frontend
    spec:
      imagePullSecrets:      # <--- 추가
        - name: ghcr-secret  # <--- 추가
      containers:
        - name: frontend
          image: ghcr.io/team-murro/murro-labs/frontend:4963fcf9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: NEXT_PUBLIC_API_URL
              value: "https://murro.co.kr"  # 기존에 있던 거라면 유지
            - name: ADMIN_USER
              value: "admin"                # 원하는 ID
            - name: ADMIN_PASSWORD
              value: "!djemals12#" # 원하는 비밀번호 (복잡하게 설정하세요!)
---
apiVersion: v1
kind: Service
metadata:
  name: murro-frontend-svc
spec:
  selector:
    app: murro-frontend
  ports:
    - port: 80
      targetPort: 3000
