apiVersion: apps/v1
kind: Deployment
metadata:
  name: murro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murro-frontend
  template:
    metadata:
      labels:
        app: murro-frontend
    spec:
      imagePullSecrets:      # <--- 추가
        - name: ghcr-secret  # <--- 추가
      containers:
        - name: frontend
          image: ghcr.io/team-murro/murro-labs/frontend:f39cfbb2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: "Asia/Seoul"
---
apiVersion: v1
kind: Service
metadata:
  name: murro-frontend-svc
spec:
  selector:
    app: murro-frontend
  ports:
    - port: 80
      targetPort: 3000
